"""add user_settings

Revision ID: 87623744c40c
Revises: 004
Create Date: 2025-11-27 12:06:26.660763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87623744c40c'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_accounts_type')
        batch_op.drop_index('idx_accounts_user_id')
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_budgets_category_id')
        batch_op.drop_index('idx_budgets_month')
        batch_op.drop_index('idx_budgets_user_id')
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=True)
        batch_op.drop_index('idx_categories_parent_id')
        batch_op.drop_index('idx_categories_type')
        batch_op.drop_index('idx_categories_user_id')
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_import_profiles_user_id')
        batch_op.drop_constraint('uq_import_profile_user_name', type_='unique')
        batch_op.create_index(batch_op.f('ix_import_profiles_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('import_value_mappings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('profile_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('internal_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_import_value_mappings_lookup')
        batch_op.drop_constraint('uq_import_value_mapping', type_='unique')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_tags_name')
        batch_op.drop_index('idx_tags_user_id')
        batch_op.create_index(batch_op.f('ix_tags_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.alter_column('transaction_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_transaction_tags_tag_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)
        batch_op.drop_index('idx_transactions_account_id')
        batch_op.drop_index('idx_transactions_category_id')
        batch_op.drop_index('idx_transactions_date')
        batch_op.drop_index('idx_transactions_type')
        batch_op.drop_index('idx_transactions_user_id')
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.create_index('idx_transactions_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_transactions_type', ['type'], unique=False)
        batch_op.create_index('idx_transactions_date', ['date'], unique=False)
        batch_op.create_index('idx_transactions_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_transactions_account_id', ['account_id'], unique=False)
        batch_op.alter_column('account_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('transaction_tags', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_tags_tag_id', ['tag_id'], unique=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_user_id'))
        batch_op.create_index('idx_tags_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_tags_name', ['name'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('import_value_mappings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_import_value_mapping', ['profile_id', 'mapping_type', 'csv_value'])
        batch_op.create_index('idx_import_value_mappings_lookup', ['profile_id', 'mapping_type'], unique=False)
        batch_op.alter_column('internal_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('profile_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('import_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_profiles_user_id'))
        batch_op.create_unique_constraint('uq_import_profile_user_name', ['user_id', 'name'])
        batch_op.create_index('idx_import_profiles_user_id', ['user_id'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.create_index('idx_categories_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_categories_type', ['type'], unique=False)
        batch_op.create_index('idx_categories_parent_id', ['parent_id'], unique=False)
        batch_op.alter_column('parent_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.create_index('idx_budgets_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_budgets_month', ['month'], unique=False)
        batch_op.create_index('idx_budgets_category_id', ['category_id'], unique=False)
        batch_op.alter_column('category_id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))
        batch_op.create_index('idx_accounts_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_accounts_type', ['type'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.drop_table('user_settings')
    # ### end Alembic commands ###








